print("Benvingut!")
print("                  MENU                     ")
print("-Tria entre les següents opcions:")
print("Opcio 1: Afegir canço")
print("Opcio 2: Registrar un usuari")
print("Opcio 3: Veure cançons disponibles")
print("Opcio 4: Veure usuaris del sistema")
print("Opcio 5: sortir del programa")
print("           -(Opcio 1: Afegir canço 1)-               ")
Canço1=input("Introdueix cançó:")
Autor1=input("Introdueix autor")
Anydellançament1=input("Introdueix any de llançament")
Estildemusica1=input("Introdueix estil de musica")
print("           -(Opcio 1: Afegir canço 2)-               ")
Canço2=input("Introdueix cançó:")
Autor2=input("Introdueix autor")
Anydellançament2=input("Introdueix any de llançament")
Estildemusica2=input("Introdueix estil de musica")
print("           -(Opcio 2: Registrar usuari 1)-")
Nomcomplet1=input("Introdueix el nom")
Datadenaixement1=input("Introdueix data de naixement")
Correuelctronic1=input("Introdueix correu elctronic")
Poblacio1=input("Introdueix la poblacio on viu")
print("           -(Opcio 2: Registrar usuari 2)-")
Nomcomplet2=input("Introdueix el nom")
Datadenaixement2=input("Introdueix data de naixement")
Correuelctronic2=input("Introdueix correu elctronic")
Poblacio2=input("Introdueix la poblacio on viu")
print("           -(Opcio 3: Cançons disponibles: Canço 1)-")
print("·Canço:" +Canço1)
print("·Autor:" +Autor1)
print("·Any de llançament:" +Anydellançament1)
print("·Estil de musica:" +Estildemusica1)
print("           -(Opcio 3: Cançons disponibles: Canço 2)-")
print("·Canço:" +Canço2)
print("·Autor:" +Autor2)
print("·Any de llançament:" +Anydellançament2)
print("·Estil de musica:" +Estildemusica2)
print("           -(Opcio 4: Usuaris del sistema: Usuari 1)-")
print("·Nom complet:" +Nomcomplet1)
print("·Data de naixement:" +Datadenaixement1)
print("·Correu electronic:" +Correuelctronic1)
print("·Poblacio:" +Poblacio1)
print("           -(Opcio 4: Usuaris del sistema: Usuari 2)-")
print("·Nom complet:" +Nomcomplet2)
print("·Data de naixement:" +Datadenaixement2)
print("·Correu electronic:" +Correuelctronic2)
print("·Poblacio:" +Poblacio2)
print("           -(Opcio 5: Sortir del programa)-")